name: publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy
        run: |
          gcloud run deploy sxta \
          --region asia-east1 \
          --source
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
